# Generated by Django 3.1.6 on 2021-02-14 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_deposit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='deposit_amount',
            new_name='amount',
        ),
    ]
