# Generated by Django 3.1.6 on 2021-02-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20210214_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='d_user_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
