# Generated by Django 3.1.6 on 2021-02-14 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_deposit_d_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='account_number',
            new_name='dep_account_number',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='d_user_name',
        ),
    ]
