# Generated by Django 3.1.6 on 2021-02-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_deposit_dep_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='dep_user_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
