# Generated by Django 3.1.6 on 2021-02-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_deposit_dep_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='dep_account',
            field=models.IntegerField(default=0),
        ),
    ]
